/**
 * AI Message Bubble Component
 * Displays user and AI message bubbles with structured content
 */

import React from 'react';
import { View, StyleSheet, Pressable } from 'react-native';
import { Text } from '@/components/shared-ui';
import { BrandColors, BorderRadius, Spacing, FontFamily, Shadows } from '@/constants/theme';
import { Copy, Volume2, ThumbsUp, ThumbsDown, RotateCcw } from 'lucide-react-native';
import type { ChatMessage, MessageSection, FunctionCall } from '@/services/types/ai.types';

interface AIMessageBubbleProps {
  message: ChatMessage;
  onCopy?: () => void;
  onSpeak?: () => void;
  onLike?: () => void;
  onDislike?: () => void;
  onRegenerate?: () => void;
  onFindMechanics?: (serviceType: string, urgency: string) => void;
}

export function AIMessageBubble({
  message,
  onCopy,
  onSpeak,
  onLike,
  onDislike,
  onRegenerate,
  onFindMechanics,
}: AIMessageBubbleProps) {
  const isUser = message.role === 'user';

  return (
    <View style={[styles.container, isUser && styles.userContainer]}>
      {/* Avatar */}
      <View style={[styles.avatar, isUser && styles.userAvatar]}>
        <Text style={styles.avatarText} size="xs">
          {isUser ? '👤' : '🤖'}
        </Text>
      </View>

      {/* Message Content */}
      <View style={styles.contentWrapper}>
        {/* Main bubble */}
        <View style={[styles.bubble, isUser && styles.userBubble]}>
          <Text style={[styles.messageText, isUser && styles.userMessageText]}>
            {message.content}
          </Text>
        </View>

        {/* Sections (AI only) */}
        {!isUser && message.sections && message.sections.length > 0 && (
          <View style={styles.sectionsContainer}>
            {message.sections.map((section, index) => (
              <MessageSectionView key={index} section={section} />
            ))}
          </View>
        )}

        {/* Diagnosis Card (AI only) */}
        {!isUser && message.functionCall && (
          <DiagnosisCard
            functionCall={message.functionCall}
            onFindMechanics={onFindMechanics}
          />
        )}

        {/* Action Buttons (AI only) */}
        {!isUser && (
          <View style={styles.actionsContainer}>
            <View style={styles.actionButtons}>
              <ActionButton icon={<Copy size={16} color="#9CA3AF" />} onPress={onCopy} />
              <ActionButton icon={<Volume2 size={16} color="#9CA3AF" />} onPress={onSpeak} />
              <ActionButton icon={<ThumbsUp size={16} color="#9CA3AF" />} onPress={onLike} />
              <ActionButton icon={<ThumbsDown size={16} color="#9CA3AF" />} onPress={onDislike} />
              <ActionButton icon={<RotateCcw size={16} color="#9CA3AF" />} onPress={onRegenerate} />
            </View>
            <Text style={styles.disclaimer} size="xs">
              Generated by AI. Double-check for accuracy.
            </Text>
          </View>
        )}
      </View>
    </View>
  );
}

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

function MessageSectionView({ section }: { section: MessageSection }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle} size="xs" weight="bold">
        {section.title.toUpperCase()}
      </Text>
      
      {section.type === 'list' && section.items ? (
        <View style={styles.listContainer}>
          {section.items.map((item, index) => (
            <View key={index} style={styles.listItem}>
              <Text style={styles.listArrow}>→</Text>
              <Text style={styles.listText}>{item}</Text>
            </View>
          ))}
        </View>
      ) : (
        <Text style={styles.sectionContent}>{section.content}</Text>
      )}
    </View>
  );
}

function DiagnosisCard({
  functionCall,
  onFindMechanics,
}: {
  functionCall: FunctionCall;
  onFindMechanics?: (serviceType: string, urgency: string) => void;
}) {
  const args = functionCall.arguments;
  if (!args.diagnosis) return null;

  const urgencyColors = {
    immediate: '#EF4444',
    soon: '#F59E0B',
    routine: '#22C55E',
  };

  return (
    <View style={styles.diagnosisCard}>
      <Text style={styles.sectionTitle} size="xs" weight="bold">
        DIAGNOSIS
      </Text>
      
      <View style={styles.diagnosisHeader}>
        <Text style={styles.diagnosisText} weight="semiBold">
          {args.diagnosis}
        </Text>
        {args.urgency && (
          <View style={[styles.urgencyBadge, { backgroundColor: urgencyColors[args.urgency] + '20' }]}>
            <Text style={[styles.urgencyText, { color: urgencyColors[args.urgency] }]}>
              {args.urgency.toUpperCase()}
            </Text>
          </View>
        )}
      </View>

      {args.estimated_cost_min && args.estimated_cost_max && (
        <View style={styles.costContainer}>
          <Text style={styles.costIcon}>💰</Text>
          <View>
            <Text style={styles.costRange}>
              ${args.estimated_cost_min} - ${args.estimated_cost_max}
            </Text>
            <Text style={styles.costLabel}>Estimated cost range</Text>
          </View>
        </View>
      )}

      {onFindMechanics && (
        <Pressable
          style={styles.findMechanicsBtn}
          onPress={() => onFindMechanics(
            args.recommended_services?.[0] || 'General Repair',
            args.urgency || 'routine'
          )}
        >
          <Text style={styles.findMechanicsBtnText}>📍 Find Nearby Mechanics</Text>
        </Pressable>
      )}
    </View>
  );
}

function ActionButton({
  icon,
  onPress,
}: {
  icon: React.ReactNode;
  onPress?: () => void;
}) {
  return (
    <Pressable
      style={({ pressed }) => [styles.actionBtn, pressed && styles.actionBtnPressed]}
      onPress={onPress}
    >
      {icon}
    </Pressable>
  );
}

// ============================================================================
// STYLES
// ============================================================================

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.md,
  },
  userContainer: {
    flexDirection: 'row-reverse',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: BrandColors.secondary + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.sm,
  },
  userAvatar: {
    backgroundColor: BrandColors.primary + '20',
    marginRight: 0,
    marginLeft: Spacing.sm,
  },
  avatarText: {
    fontSize: 14,
  },
  contentWrapper: {
    flex: 1,
    maxWidth: '85%',
  },
  bubble: {
    backgroundColor: BrandColors.white,
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    ...Shadows.sm,
  },
  userBubble: {
    backgroundColor: BrandColors.secondary,
    borderColor: 'transparent',
  },
  messageText: {
    color: BrandColors.primary,
    lineHeight: 22,
  },
  userMessageText: {
    color: BrandColors.white,
  },
  sectionsContainer: {
    marginTop: Spacing.sm,
    gap: Spacing.sm,
  },
  section: {
    backgroundColor: BrandColors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: BrandColors.secondary,
    ...Shadows.sm,
  },
  sectionTitle: {
    color: BrandColors.secondary,
    marginBottom: Spacing.xs,
    letterSpacing: 0.5,
  },
  sectionContent: {
    color: BrandColors.primary,
    lineHeight: 22,
  },
  listContainer: {
    gap: Spacing.xs,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  listArrow: {
    color: BrandColors.secondary,
    marginRight: Spacing.sm,
    fontSize: 14,
  },
  listText: {
    flex: 1,
    color: BrandColors.primary,
    lineHeight: 22,
  },
  diagnosisCard: {
    backgroundColor: BrandColors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginTop: Spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: BrandColors.secondary,
    ...Shadows.sm,
  },
  diagnosisHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  diagnosisText: {
    color: BrandColors.primary,
    fontSize: 16,
  },
  urgencyBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  urgencyText: {
    fontSize: 10,
    fontFamily: FontFamily.bold,
    letterSpacing: 0.5,
  },
  costContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: '#FEF3C7',
    padding: Spacing.sm,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
  },
  costIcon: {
    fontSize: 20,
  },
  costRange: {
    color: '#92400E',
    fontFamily: FontFamily.semiBold,
    fontSize: 16,
  },
  costLabel: {
    color: '#92400E',
    fontSize: 12,
  },
  findMechanicsBtn: {
    backgroundColor: BrandColors.secondary,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
  },
  findMechanicsBtnText: {
    color: BrandColors.white,
    fontFamily: FontFamily.semiBold,
    fontSize: 14,
  },
  actionsContainer: {
    marginTop: Spacing.sm,
    paddingLeft: Spacing.xs,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  actionBtn: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: BorderRadius.md,
  },
  actionBtnPressed: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },
  disclaimer: {
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
});

